"""Serve recorded footage as genuine RTSP, via MediaMTX.

This closes the last gap between the demonstration and a real deployment. Until
now Prahari's demo cameras produced frames in-process; here they arrive over the
wire as RTSP, decoded by the same `StreamSource` that talks to an actual camera
on a pole. Nothing in the pipeline above the source layer changes, which is the
point of having had a source layer.

Why MediaMTX rather than an RTSP server written here: it is the same component
you would deploy in front of real cameras. Its documented role is proxying and
re-streaming existing RTSP sources, which is exactly the retrofit topology
Prahari targets - point it at the cameras or at the site's existing recorder, and
Prahari consumes one well-behaved endpoint per camera instead of competing for
the camera's limited client slots.

Streams are started **on demand**: MediaMTX launches the ffmpeg process only when
something actually connects, and stops it when the last reader disconnects. That
is both cheaper and a closer match to how a real proxy behaves.
"""
from __future__ import annotations

import logging
import os
import platform
import shutil
import signal
import subprocess
import time
from pathlib import Path
from typing import Any

log = logging.getLogger("prahari.rtsp")

DEFAULT_RTSP_PORT = 8554
# MediaMTX's own HTTP API, used to confirm the server is up and list paths.
DEFAULT_API_PORT = 9997


def find_mediamtx(root: Path) -> Path | None:
    """Locate the MediaMTX executable, preferring the vendored copy."""
    exe = "mediamtx.exe" if platform.system() == "Windows" else "mediamtx"
    candidates = [
        root / "vendor" / "mediamtx" / exe,
        root / "vendor" / exe,
        root / exe,
    ]
    for c in candidates:
        if c.exists():
            return c
    found = shutil.which("mediamtx")
    return Path(found) if found else None


def find_ffmpeg() -> str | None:
    """Locate an ffmpeg binary.

    Prefers the one bundled by imageio-ffmpeg, because it arrives through pip
    rather than as a separate manual download - one fewer thing to install by
    hand on a machine that has to be set up quickly.
    """
    try:
        import imageio_ffmpeg

        exe = imageio_ffmpeg.get_ffmpeg_exe()
        if exe and Path(exe).exists():
            return exe
    except Exception:
        pass
    return shutil.which("ffmpeg")


def build_config(
    footage: dict[str, Path],
    ffmpeg: str,
    *,
    rtsp_port: int = DEFAULT_RTSP_PORT,
    api_port: int = DEFAULT_API_PORT,
    transcode: bool = True,
) -> str:
    """Generate a MediaMTX configuration serving one path per camera.

    `runOnDemand` means ffmpeg is only launched when a reader connects. The
    `-re` flag paces the file at its real frame rate, so the stream behaves like
    a live camera rather than delivering the whole file as fast as the disk can
    read it - without it the pipeline would see an hour of footage in seconds and
    every temporal measurement, from frame rate to dwell time, would be wrong.
    """
    lines = [
        "# Generated by prahari.edge.rtsp_serve - do not edit by hand.",
        "#",
        "# Serves recorded footage as RTSP so Prahari ingests over the wire,",
        "# through the same code path that reads a real camera.",
        "",
        "logLevel: info",
        "logDestinations: [stdout]",
        "readTimeout: 15s",
        "writeTimeout: 15s",
        "",
        f"rtsp: yes",
        f"rtspAddress: :{rtsp_port}",
        "rtspTransports: [tcp]",
        "",
        "api: yes",
        f"apiAddress: 127.0.0.1:{api_port}",
        "",
        "# Everything else off: this is a demonstration source, not a media server.",
        "rtmp: no",
        "hls: no",
        "webrtc: no",
        "srt: no",
        "",
        "paths:",
    ]

    # Forward slashes throughout. A Windows path inside a YAML scalar is a trap:
    # a value starting with a drive letter and backslashes is read as a
    # double-quoted scalar, and YAML then treats \U, \S and friends as escape
    # sequences and refuses to parse the file at all. ffmpeg accepts forward
    # slashes on Windows perfectly well.
    ffmpeg_path = str(ffmpeg).replace("\\", "/")

    for name, path in sorted(footage.items()):
        src = str(path.resolve()).replace("\\", "/")
        if transcode:
            # The recordings are MPEG-4 Part 2 (what OpenCV can write here).
            # Transcode to H.264, which is what every IP camera actually emits
            # and what RTSP consumers expect. ultrafast keeps the CPU cost off
            # the analytics, which is what the machine is really for.
            codec = ("-c:v libx264 -preset ultrafast -tune zerolatency "
                     "-pix_fmt yuv420p -g 24 -bf 0")
        else:
            codec = "-c:v copy"
        cmd = (
            f'"{ffmpeg_path}" -hide_banner -loglevel error -re -stream_loop -1 '
            f'-i "{src}" {codec} -an -f rtsp '
            f"rtsp://127.0.0.1:{rtsp_port}/{name}"
        )
        # Single-quoted YAML performs no escape processing at all, and the inner
        # double quotes the shell needs around each path survive untouched.
        cmd_yaml = "'" + cmd.replace("'", "''") + "'"
        lines += [
            f"  {name}:",
            f"    runOnDemand: {cmd_yaml}",
            "    runOnDemandRestart: yes",
            "    runOnDemandCloseAfter: 10s",
            "",
        ]

    return "\n".join(lines)


class MediaMtxServer:
    """Supervises a MediaMTX process serving the demo footage."""

    def __init__(self, root: Path, footage_dir: Path,
                 rtsp_port: int = DEFAULT_RTSP_PORT,
                 api_port: int = DEFAULT_API_PORT) -> None:
        self.root = Path(root)
        self.footage_dir = Path(footage_dir)
        self.rtsp_port = rtsp_port
        self.api_port = api_port
        self.exe = find_mediamtx(self.root)
        self.ffmpeg = find_ffmpeg()
        self.config_path = self.root / "var" / "mediamtx-prahari.yml"
        self.log_path = self.root / "var" / "mediamtx.log"
        self._proc: subprocess.Popen | None = None
        self._log_handle = None

    # -- discovery -------------------------------------------------------
    def footage(self) -> dict[str, Path]:
        """Map an RTSP path name to a recording.

        `CAM-011.mp4` is served at `rtsp://host:8554/cam-011`; lowercase because
        RTSP paths are case-sensitive and mixed case is a reliable source of
        typos at 2am.
        """
        if not self.footage_dir.exists():
            return {}
        out: dict[str, Path] = {}
        for p in sorted(self.footage_dir.glob("*.mp4")):
            out[p.stem.lower()] = p
        return out

    def preflight(self) -> list[str]:
        """Everything that would stop this working, reported at once."""
        problems = []
        if self.exe is None:
            problems.append(
                "MediaMTX not found. Expected vendor/mediamtx/mediamtx.exe - "
                "see docs/rtsp.md for how to install it."
            )
        if self.ffmpeg is None:
            problems.append(
                "ffmpeg not found. Install with: pip install imageio-ffmpeg"
            )
        if not self.footage():
            problems.append(
                f"No recordings in {self.footage_dir}/. Generate them with: "
                f"python scripts/make_footage.py"
            )
        return problems

    # -- lifecycle -------------------------------------------------------
    def start(self, transcode: bool = True) -> bool:
        problems = self.preflight()
        if problems:
            for p in problems:
                log.error("%s", p)
            return False

        assert self.exe and self.ffmpeg
        self.config_path.parent.mkdir(parents=True, exist_ok=True)
        self.config_path.write_text(
            build_config(self.footage(), self.ffmpeg,
                         rtsp_port=self.rtsp_port, api_port=self.api_port,
                         transcode=transcode),
            encoding="utf-8",
        )

        log.info("starting MediaMTX on rtsp://127.0.0.1:%d", self.rtsp_port)
        # Straight to a file, not a pipe. An unread PIPE deadlocks the child once
        # its buffer fills, and - the reason this changed - it hid the startup
        # error that explained why the child had exited at all.
        self._log_handle = self.log_path.open("w", encoding="utf-8")
        self._proc = subprocess.Popen(
            [str(self.exe), str(self.config_path)],
            cwd=str(self.root),
            stdout=self._log_handle, stderr=subprocess.STDOUT,
        )
        ok = self.wait_ready()
        if not ok:
            try:
                tail = self.log_path.read_text(encoding="utf-8")[-1500:]
                if tail.strip():
                    log.error("MediaMTX reported:\n%s", tail)
            except Exception:
                pass
        return ok

    def wait_ready(self, timeout: float = 20.0) -> bool:
        import httpx

        deadline = time.monotonic() + timeout
        while time.monotonic() < deadline:
            if self._proc and self._proc.poll() is not None:
                log.error("MediaMTX exited immediately (code %s)", self._proc.returncode)
                return False
            try:
                r = httpx.get(f"http://127.0.0.1:{self.api_port}/v3/paths/list",
                              timeout=2.0)
                if r.status_code == 200:
                    names = [p["name"] for p in r.json().get("items", [])]
                    log.info("MediaMTX ready, serving %d path(s): %s",
                             len(names), ", ".join(names))
                    return True
            except Exception:
                pass
            time.sleep(0.5)
        log.error("MediaMTX did not become ready within %.0fs", timeout)
        return False

    def stop(self) -> None:
        if self._proc is None:
            return
        try:
            if platform.system() == "Windows":
                self._proc.terminate()
            else:
                self._proc.send_signal(signal.SIGTERM)
            self._proc.wait(timeout=8)
        except Exception:
            try:
                self._proc.kill()
            except Exception:
                pass
        finally:
            self._proc = None
            if self._log_handle is not None:
                try:
                    self._log_handle.close()
                except Exception:
                    pass
                self._log_handle = None

    # -- introspection ---------------------------------------------------
    def url_for(self, name: str) -> str:
        return f"rtsp://127.0.0.1:{self.rtsp_port}/{name.lower()}"

    def status(self) -> dict[str, Any]:
        return {
            "running": self._proc is not None and self._proc.poll() is None,
            "executable": str(self.exe) if self.exe else None,
            "ffmpeg": self.ffmpeg,
            "rtsp_port": self.rtsp_port,
            "paths": {n: self.url_for(n) for n in self.footage()},
            "config": str(self.config_path),
        }
