"""End-to-end smoke test against a running edge node.

Drives the three demonstration moments and checks that each actually happened,
rather than that a button returned 200:

  1. Camera-aware analytics - different cameras end up with different granted
     capability sets, for measured reasons.
  2. Intrusion -> detection -> tracking -> rule -> scored event -> evidence, with
     the evidence file present on disk and the hash chain intact.
  3. Link failure -> detection continues -> events queue locally -> link restored
     -> queue drains, with original timestamps preserved.

Run the node first:
    .venv/Scripts/python.exe -m uvicorn prahari.edge.app:app --port 8420
then:
    .venv/Scripts/python.exe scripts/smoke_e2e.py
"""
from __future__ import annotations

import json
import sys
import time
from pathlib import Path

import httpx

BASE = "http://127.0.0.1:8420"
ROOT = Path(__file__).resolve().parents[1]

PASS = "  [PASS]"
FAIL = "  [FAIL]"
INFO = "        "

failures: list[str] = []


def check(label: str, ok: bool, detail: str = "") -> bool:
    print(f"{PASS if ok else FAIL} {label}")
    if detail:
        print(f"{INFO} {detail}")
    if not ok:
        failures.append(label)
    return ok


def main() -> int:
    pw_file = ROOT / "var" / ".demo_admin_pw"
    if not pw_file.exists():
        print("No admin password captured. Start the node and save the printed")
        print("password to var/.demo_admin_pw, or re-run scripts/run_demo.sh.")
        return 2
    password = pw_file.read_text().strip()

    client = httpx.Client(base_url=BASE, timeout=30.0)

    # --- auth -----------------------------------------------------------
    r = client.post("/api/auth/login",
                    json={"username": "admin", "password": password})
    check("authentication", r.status_code == 200, f"HTTP {r.status_code}")
    if r.status_code != 200:
        return 1
    token = r.json()["token"]
    client.headers["Authorization"] = f"Bearer {token}"

    # --- 1. camera-aware analytics ---------------------------------------
    print("\n=== 1. Camera capability profiling ===")
    cams = client.get("/api/cameras").json()["cameras"]
    grants: dict[str, set] = {}
    for c in cams:
        rt = c.get("runtime") or {}
        grants[c["camera_id"]] = set(rt.get("granted") or [])
        print(f"{INFO} {c['camera_id']:<9} {str(rt.get('dori')):<10} "
              f"{len(grants[c['camera_id']]):>2} granted   {c['role']}")

    distinct = {frozenset(v) for v in grants.values()}
    check("cameras receive different capability sets",
          len(distinct) > 1,
          f"{len(distinct)} distinct capability sets across {len(cams)} cameras")

    anpr_cams = [cid for cid, g in grants.items() if "anpr" in g]
    check("ANPR is granted selectively, not universally",
          0 < len(anpr_cams) < len(cams),
          f"granted on {anpr_cams or 'none'}")

    face_rec = [cid for cid, g in grants.items() if "face_recognition" in g]
    check("face recognition is never auto-granted",
          len(face_rec) == 0,
          "withheld by product policy on every camera")

    # Every refusal must carry a measured reason.
    cert = client.get(f"/api/cameras/{cams[1]['camera_id']}/certificate").json()
    refusals = [g for g in cert["grants"] if not g["granted"]]
    check("every refusal carries a stated reason",
          all(g.get("reason") for g in refusals),
          f"{len(refusals)} refusals on {cams[1]['camera_id']}, all explained")
    check("capability certificate digest verifies",
          cert.get("digest_valid") is True)

    # --- 2. intrusion -> event -> evidence --------------------------------
    print("\n=== 2. Intrusion to evidence-backed event ===")
    before = client.get("/api/events?limit=1").json()["total"]
    r = client.post("/api/demo/action",
                    json={"action": "intrusion", "camera_id": "CAM-014"})
    check("intrusion injected into the simulated scene", r.status_code == 200,
          r.json().get("note", ""))

    print(f"{INFO} waiting for the subject to walk to the fence and cross it...")
    event = None
    for _ in range(60):
        time.sleep(2)
        evs = client.get("/api/events?limit=20&camera_id=CAM-014").json()["events"]
        crossing = [e for e in evs
                    if e["event_type"] in ("line_crossing", "zone_intrusion")]
        if crossing:
            event = crossing[0]
            break

    if not check("a border event was generated by the rule engine", event is not None):
        print(f"{INFO} events now: {client.get('/api/events?limit=1').json()['total']} "
              f"(was {before})")
    else:
        print(f"{INFO} {event['event_type']}  priority={event['priority']} "
              f"score={event['priority_score']}")
        print(f"{INFO} {event['summary']}")
        check("event carries an explainable score",
              len(event.get("priority_factors") or []) >= 2,
              " | ".join(f"{f['name']} {f['weight']:+.2f}"
                         for f in event["priority_factors"]))
        check("event references the track that caused it",
              event.get("track_id") is not None,
              f"track #{event.get('track_id')}, {event.get('object_class')}")

        ev_id = event["event_id"]
        fr = client.get(f"/api/events/{ev_id}/evidence/frame")
        check("trigger frame evidence is retrievable",
              fr.status_code == 200 and len(fr.content) > 1000,
              f"{len(fr.content)} bytes, sha256 "
              f"{(event.get('evidence') or {}).get('frame_sha256', '')[:16]}...")

        print(f"{INFO} waiting for the post-roll clip to finalise...")
        clip_ok = False
        for _ in range(20):
            time.sleep(2)
            cl = client.get(f"/api/events/{ev_id}/evidence/clip")
            if cl.status_code == 200 and len(cl.content) > 2000:
                clip_ok = True
                detail = f"{len(cl.content)} bytes"
                break
        else:
            detail = "clip did not finalise within 40 s"
        check("evidence clip with pre-roll was written", clip_ok, detail)

    led = client.get("/api/system/ledger/verify").json()
    check("evidence hash chain verifies", led.get("valid") is True, led.get("message", ""))

    # --- 3. offline operation and store-and-forward ------------------------
    print("\n=== 3. Link failure and store-and-forward ===")
    r = client.post("/api/demo/action", json={"action": "network_outage"})
    check("link taken down", r.status_code == 200, r.json().get("note", ""))

    pending_before = client.get("/api/system/status").json()["events_pending_sync"]
    client.post("/api/demo/action",
                json={"action": "intrusion", "camera_id": "CAM-022"})
    client.post("/api/demo/action",
                json={"action": "group", "camera_id": "CAM-014", "size": 4})

    print(f"{INFO} detecting while offline...")
    time.sleep(30)

    st = client.get("/api/system/status").json()
    check("link reported as down", st["link_mode"] == "offline",
          f"link_mode={st['link_mode']}")
    check("detection continued while offline",
          st["cameras_online"] > 0,
          f"{st['cameras_online']}/{st['cameras_total']} cameras still running")
    pending_after = st["events_pending_sync"]
    check("events queued locally during the outage",
          pending_after >= pending_before,
          f"{pending_before} -> {pending_after} pending")

    queued = client.get("/api/events?limit=5").json()["events"]
    original_stamps = {e["event_id"]: e["timestamp"] for e in queued}

    r = client.post("/api/demo/action", json={"action": "network_restore"})
    check("link restored", r.status_code == 200)
    print(f"{INFO} draining the queue...")
    time.sleep(6)

    st2 = client.get("/api/system/status").json()
    sync = st2.get("sync") or client.get("/api/system/status").json()["sync"]
    print(f"{INFO} link_mode={st2['link_mode']}  pending={st2['events_pending_sync']}  "
          f"core_reachable={sync['core_reachable']}")
    check("link mode recovered from offline",
          st2["link_mode"] != "offline",
          f"now {st2['link_mode']}"
          + ("" if sync["core_reachable"]
             else "  (no sector core running - see note below)"))

    now = client.get("/api/events?limit=5").json()["events"]
    preserved = all(e["timestamp"] == original_stamps.get(e["event_id"],
                                                          e["timestamp"])
                    for e in now)
    check("original timestamps preserved across the outage", preserved)

    bw = client.get("/api/system/bandwidth").json()
    print(f"\n{INFO} bandwidth: observed {bw['bytes_observed']/1e6:.1f} MB of imagery, "
          f"transmitted {bw['bytes_transmitted']/1e3:.1f} kB "
          f"({bw['reduction_percent']:.2f}% reduction)")
    print(f"{INFO} {bw['basis']}")

    # --- summary -----------------------------------------------------------
    print("\n" + "=" * 70)
    if failures:
        print(f"FAILED: {len(failures)} check(s)")
        for f in failures:
            print(f"  - {f}")
    else:
        print("All checks passed.")
    print("=" * 70)
    return 1 if failures else 0


if __name__ == "__main__":
    raise SystemExit(main())
